- script/seed.js
- server/db/models/order.js
- server/db/models/product.js
- server/index.js
> done with seed file

- client/components/Products.js
- client/components/auth-form.js
- client/store/user.js
- server/auth/index.js
> update form to include name

- client/store/user.js
> add guest object

- client/components/SingleCategory.js
- client/routes.js
> minor changes to SingleCategory

- package-lock.json
- server/api/categories.js
> fixed include

- client/components/SingleCategory.js
> minor changes

- client/components/SingleCategory.js
- package-lock.json
> li tag fix

- client/components/OrderReview.js
- client/components/SingleProduct.js
- client/store/index.js
- client/store/reviews.js
- package-lock.json
- package.json
- server/api/reviews.js
- server/db/models/index.js
> single product done

- client/components/ShoppingCart.js
> submit button navigates to order review page

- client/components/MyAccount.js
- client/components/index.js
> myaccount 

- client/components/MyAccount.js
- client/store/orders.js
- server/api/orders.js
wanted to push before they looked at my comp.  page includes user orders filter(may be hard to test without adding entries into database.
##ssignee Tasks
---
> myaccount added order filter

- package-lock.json
- server/auth/google.js
> got google oAuth working

- client/components/OrderReview.js
- client/components/Products.js
> All products

- client/components/OrderReview.js
> order review functioning

- client/components/MyAccount.js
- client/components/SingleOrder.js
- client/components/index.js
- client/routes.js
- client/store/index.js
- client/store/singleOrder.js
Let's def discuss admin stuff tom.
---
> revised myaccount page to link to orders and added view single Order

- client/components/OrderConfirmation.js
- client/store/email.js
- client/store/index.js
- server/api/email.js
- server/api/index.js
- server/index.js
> confimation page works still working on email

- client/components/SingleOrder.js
- client/store/orders.js
- server/api/index.js
- server/api/orders.js
> added change order status by admin on order detail page

- client/components/MyAccount.js
- client/store/orders.js
> admin can now see all user orders and sort on myAccount page

- client/components/OrderConfirmation.js
- client/components/OrderReview.js
- package-lock.json
- server/api/email.js
- server/index.js
> rough email working

- client/components/SingleProduct.js
- client/store/products.js
- client/store/singleProduct.js
- server/api/products.js
> added admin update product details

- client/components/MyAccount.js
- client/store/adminUsers.js
- client/store/index.js
- client/store/user.js
- server/api/users.js
> delete and update user as admin

- client/components/SingleProduct.js
- client/store/reviews.js
- package-lock.json
- server/db/models/index.js
> adjust new review state

- client/components/Navbar.js
> Add my account button to nav

- package.json
moved chance from devDependencies >>> dependencies
> move chance to dependencies

- package.json
> move chance

- package.json
> adding chance to dependencies

- client/components/SingleCategory.js
- client/components/SingleProduct.js
- server/api/orders.js
- server/api/products.js
- server/api/reviews.js
- server/api/users.js
- server/middleware.js
> admin routes done

- client/components/SingleProduct.js
> fixed reviews that i broke

- client/components/MyAccount.js
- server/api/orders.js
- server/middleware.js
> fix user routes

- client/components/AddProduct.js
- client/components/MyAccount.js
- client/components/SingleProduct.js
- client/store/products.js
- client/store/singleProduct.js
- server/api/products.js
> addproduct form

- client/components/SingleProduct.js
> fixed merge errors

- client/components/Navbar.js
- client/store/user.js
> logout redirects to homepage now

- client/components/ShoppingCart.js
> possibly fixed cart bug

- client/components/MyAccount.js
> adminStuff

- client/components/AddProduct.js
- client/components/MyAccount.js
- client/components/SingleProduct.js
- public/style.css
> added form stylin' and some dropdown thing

- client/components/AddCategory.js
- client/components/AddProduct.js
- client/components/MyAccount.js
- client/components/SingleProduct.js
- public/style.css
> made add category section to conform with others.

- client/components/AddCategory.js
- client/components/AddProduct.js
- client/components/MyAccount.js
> fixing things

- client/components/OrderReview.js
- public/style.css
> updated css on order review

- script/seed.js
> new seed photots

- script/seed.js
> added pictures

- client/components/Home.js
- package-lock.json
- package.json
> homepage update
